In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

scalar = 3.7
array = np.array([2.5, -1.2, 3.6, 0.0, -4.7, 1.8])  # Custom 6-element array

print("Original array:", array)

# Trigonometric functions
print("sin(array):", np.sin(array))
print("cos(array):", np.cos(array))
print("tan(array):", np.tan(array))




Original array: [ 2.5 -1.2  3.6  0.  -4.7  1.8]
sin(array): [ 0.59847214 -0.93203909 -0.44252044  0.          0.99992326  0.97384763]
cos(array): [-0.80114362  0.36235775 -0.89675842  1.         -0.01238866 -0.22720209]
tan(array): [ -0.7470223   -2.57215162   0.49346673   0.         -80.71276297
  -4.28626167]


In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

matrix = np.array([[1.2, -3.4], [0.5, 2.6], [-1.0, 4.8]])
print("Matrix:\n", matrix)

# Trigonometric
print("sin:", np.sin(matrix))
print("cos:", np.cos(matrix))
print("tan:", np.tan(matrix))

# Exponential & Logarithmic
print("exp:\n", np.exp(matrix))
print("log (clipped > 0.1):\n", np.log(np.clip(matrix, 0.1, None)))

# Absolute value & Square root
print("abs:\n", np.abs(matrix))
print("sqrt (abs):\n", np.sqrt(np.abs(matrix)))

# Remainder when divided by 2
print("remainder % 2:\n", np.remainder(matrix, 2))

# Rounding
print("round:\n", np.round(matrix))
print("floor:\n", np.floor(matrix))
print("ceil:\n", np.ceil(matrix))

Matrix:
 [[ 1.2 -3.4]
 [ 0.5  2.6]
 [-1.   4.8]]
sin: [[ 0.93203909  0.2555411 ]
 [ 0.47942554  0.51550137]
 [-0.84147098 -0.99616461]]
cos: [[ 0.36235775 -0.96679819]
 [ 0.87758256 -0.85688875]
 [ 0.54030231  0.08749898]]
tan: [[  2.57215162  -0.2643169 ]
 [  0.54630249  -0.60159661]
 [ -1.55740772 -11.38487065]]
exp:
 [[3.32011692e+00 3.33732700e-02]
 [1.64872127e+00 1.34637380e+01]
 [3.67879441e-01 1.21510418e+02]]
log (clipped > 0.1):
 [[ 0.18232156 -2.30258509]
 [-0.69314718  0.95551145]
 [-2.30258509  1.56861592]]
abs:
 [[1.2 3.4]
 [0.5 2.6]
 [1.  4.8]]
sqrt (abs):
 [[1.09544512 1.84390889]
 [0.70710678 1.61245155]
 [1.         2.19089023]]
remainder % 2:
 [[1.2 0.6]
 [0.5 0.6]
 [1.  0.8]]
round:
 [[ 1. -3.]
 [ 0.  3.]
 [-1.  5.]]
floor:
 [[ 1. -4.]
 [ 0.  2.]
 [-1.  4.]]
ceil:
 [[ 2. -3.]
 [ 1.  3.]
 [-1.  5.]]


In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

vector_matrix = np.array([[2.1, 4.7, 3.3],
                          [1.9, 5.6, 0.8]])

print("\n2x3 Vector Matrix:\n", vector_matrix)

# Max & Min with indices
print("Max value:", np.max(vector_matrix))
print("Min value:", np.min(vector_matrix))
print("Index of Max:", np.unravel_index(np.argmax(vector_matrix), vector_matrix.shape))
print("Index of Min:", np.unravel_index(np.argmin(vector_matrix), vector_matrix.shape))

# Vector length (L2 Norm)
print("Vector length:", np.linalg.norm(vector_matrix))

# Sorting
print("Row-wise sorted descending:\n", np.sort(vector_matrix)[:, ::-1])
print("Entire matrix sorted descending:\n", np.sort(vector_matrix.flatten())[::-1])

# Sum, Product
print("Sum:", np.sum(vector_matrix))
print("Product:", np.prod(vector_matrix))

# Median, Mean, Standard Deviation
print("Median:", np.median(vector_matrix))
print("Mean:", np.mean(vector_matrix))
print("Standard Deviation:", np.std(vector_matrix))


2x3 Vector Matrix:
 [[2.1 4.7 3.3]
 [1.9 5.6 0.8]]
Max value: 5.6
Min value: 0.8
Index of Max: (np.int64(1), np.int64(1))
Index of Min: (np.int64(1), np.int64(2))
Vector length: 8.54400374531753
Row-wise sorted descending:
 [[4.7 3.3 2.1]
 [5.6 1.9 0.8]]
Entire matrix sorted descending:
 [5.6 4.7 3.3 2.1 1.9 0.8]
Sum: 18.400000000000002
Product: 277.24435200000005
Median: 2.7
Mean: 3.066666666666667
Standard Deviation: 1.6619934483090546
